FROM node:latest

RUN apt-get upgrade && \
apt-get install npm && \
apt-get install git

RUN git clone https://github.com/vss-2/termus
WORKDIR /termus/backend
RUN npm install
RUN node backend.js
EXPOSE 8080
